### ISSUE TITLE
Commands not properly constructed in some cases

### ISSUE THREAD

**Issue by carueda** [mbari-org/dash5#246]
**Describe the bug**
Commands not properly constructed in some cases

**To Reproduce**
1. Try to issue a `failComponent` command to some vehicle (say `sim`)
4. Error is displayed at the last step.

**Expected behavior**
No error, just the command successfully issued.

**Additional context**

The request is reflected like this in the backend:
```
2023-03-28 15:06:15,507 (http-nio-8080-exec-19) DEBUG [o.m.t.r.s.CommandRouteHandler] - sendCommands:
  vehicle=sim
  commandText=sched asap ""
  commandNote=
  schedDate=asap
  schedId=2b6qf (server generated)
  runCommand=false
  email=carueda@mbari.org
  destinationAddress=null
```

It is `commandText=sched asap ""` piece that clearly indicates the command was not properly formed.

**Comment by jimjeffers** [comment]
@carueda I was able to replicate the issue. It looks like the default selection is not carrying over in the wizard state. If you choose an alternative template of the command and then select the default failComponent template the proper `sched asap` gets sent to the API. We just need to fix the default state on the command step to ensure it's carried over to the next step in the wizard.

<img width="1026" alt="CleanShot 2023-03-28 at 15 45 15@2x" src="https://user-images.githubusercontent.com/9150/228383601-15e90bfd-1856-4b98-8fc0-a98dd3ba440b.png">

**Comment by jimjeffers** [comment]
@ksalamy I believe this is the line you're going to be looking for:
https://github.com/mbari-org/dash5/blob/0b527bff294ea6e20a4070bf4612198680a57503/packages/react-ui/src/Modals/CommandModal.tsx#L178

I think setting the initial state to `syntaxVariations[0]` instead of `null` might solve this. Let me know if you get blocked on this and I can dig further if need be.

**Comment by jimjeffers** [comment]
...or to be null safe 

```ts
useState<string | null>(syntaxVariations?.[0] ?? null)
```

**Comment by heavyB** [comment]
Note that dash 5 is using the schedule asap "<string>" command incorrectly. Help schedule defines appropriate use. However, just simply send "failc" rather than "schedule asap "failc"" for any asap commands. There's no need to invoke the scheduler. Please see dash 4 for appropriate syntax. 

catalina2>sched asap "failc" 
2023-04-11T22:18:45.982Z,1681251525.982 [CommandExec](IMPORTANT): got command schedule asap "failc" 
2023-04-11T22:18:45.982Z,1681251525.982 [CommandExec](FAULT): Incomplete syntax. Try: help schedule
catalina2>help schedule
catalina2>schedule: Schedule commands for later execution
List commands currently scheduled
    schedule [list]
Clear all commands currently scheduled, optionally only those with a corresponding id
    schedule clear [<id>]
Pause initiation of scheduled commands
    schedule pause
Remove single scheduled command
    schedule remove <index#>
Resume paused initiation of scheduled commands
    schedule resume
Schedule a command as soon as possible with id, idIndex, and idCount
    schedule asap <"quotedString"> <id> <idIndex> <idCount>
Schedule a command next in sequence with optional id, idIndex, and idCount
    schedule <"quotedString"> [<id> <idIndex>] <idCount>]
Schedule a command at a specific time with optional id, idIndex, and idCount
    schedule <timestamp> <"quotedString"> [<id> <idIndex>] <idCount>]
2023-04-11T22:18:49.495Z,1681251529.495 [CommandExec](IMPORTANT): got command help schedule
catalina2>failc
2023-04-11T22:18:53.709Z,1681251533.709 [CommandExec](IMPORTANT): got command failComponent
2023-04-11T22:18:53.710Z,1681251533.710 [CommandExec](IMPORTANT): Failed components:
2023-04-11T22:18:53.710Z,1681251533.710 [CommandExec](IMPORTANT): No failed Components.

**Comment by jimjeffers** [comment]
@heavyB or @carueda do you know how I should apply the logic such that certain commands do not get built with `sched asap`? I believe we toggled `asap` to be selected by default now so we'll have to add some behind the scenes logic to know which commands should not invoke the scheduler like `failc`. Is there a filter list of schedulable commands I can use so that we can check whether or not to invoke the scheduler when the user runs a given command?

**Comment by carueda** [comment]
(as a sort of summary from the slack exchanges today)

FYI Among other various additions/updates in https://docs.mbari.org/tethysdash/apidocs/, I just adjusted the parameter descriptions for `POST /api/commands`, in particular:

- `commandNote`:  actually optional (was marked as required)
- `commandText`: added note: “Do not include any scheduling information in this parameter”
- `schedDate`: Depending on how the command should be scheduled:
  - Set this to “asap” to schedule the command for execution as soon as possible
  - Set this to a date in the future to schedule the command for execution at that time.
   The format should be YYYYMMDDTHHmm (interpreted as UTC).
  - Omit this parameter if the command should just be queued for execution.
- `runCommand`:  Only pass this parameter, and with value “y”, to generate an event with type run , which is used to indicate the scheduling of a *mission*. Otherwise (if omitting this parameter or passing any other value), this request will generate an event of type command, which is for any other, non-mission-scheduling related commands.
- `schedID`: An ID for scheduling purposes. By default, a server-generated ID will be used for the subsequent request to the vehicle.
