### ISSUE TITLE
Comms queue and schedule tab not being populated when vehicle is running and not on deployment. 

### ISSUE THREAD

**Issue by heavyB** [mbari-org/dash5#281]
**Describe the bug**
It appears that when a vehicle isn't deployed that the comms and schedule tabs aren't getting populated. Compare to old dash to see what should be there. 

**To Reproduce**
1. Send a command to a vehicle
2. Note that it shows up on the old dash and not the new

**Comment by jimjeffers** [comment]
Ok so in order to address this issue we can either remove the time constraints on the API calls to the logs. That way you always have the freshest data. 

OR if we need to preserve the time based logs i.e. you jump to a deployment from 3 months ago and only want to see the logs from that deployment. Then we'll need to only omit the time constraints on the logs for the last deployment. 

In order to at least do the basic fix and remove time constraints and just resolve this issue -- simply remove or set the to/from variables to undefined on the `<LogsSection />`:
https://github.com/mbari-org/dash5/blob/7bb6c2824f3776b3c75b315f95af6e4215ed53dd/apps/lrauv-dash2/components/VehicleAccordion.tsx#LL200C27-L200C27

Again this filtering is in place to provide a behavior where you could jump back in time to a specific deployment and only see what happened relative to that deployment but it sounds like that behavior is not what the pilots need so simply removing the to/from filtering should fix this issue.

@ksalamy Let me know if you have time to tackle this or if you'd like me to submit a PR w/ a solution 

Thanks!
